/*
 * Created on 2025-01-20 ( 17:03:21 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Armor"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="armor", schema="stargrave" )
public class Armor implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="armor_id", nullable=false)
    private int        armorId ;

    //--- OTHER DATA FIELDS 
    @Column(name="equipment_type_id")
    private Integer    equipmentTypeId ;

    @Column(name="name", nullable=false, length=50)
    private String     name ;

    @Column(name="armor_modifier", nullable=false)
    private int        armorModifier ;

    @Column(name="gear_slots", nullable=false)
    private int        gearSlots ;

    @Column(name="movement_penalty")
    private Integer    movementPenalty ;

    @Column(name="notes", length=2147483647)
    private String     notes ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="equipment_type_id", referencedColumnName="equipment_type_id", insertable=false, updatable=false)
    private EquipmentTypes equipmenttypes ; 

    /**
     * Constructor
     */
    public Armor() {
		super();
    }
    
    public void setArmorId( int armorId ) {
        this.armorId = armorId ;
    }
    public int getArmorId() {
        return this.armorId;
    }

    public void setEquipmentTypeId( Integer equipmentTypeId ) {
        this.equipmentTypeId = equipmentTypeId ;
    }
    public Integer getEquipmentTypeId() {
        return this.equipmentTypeId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setArmorModifier( int armorModifier ) {
        this.armorModifier = armorModifier ;
    }
    public int getArmorModifier() {
        return this.armorModifier;
    }

    public void setGearSlots( int gearSlots ) {
        this.gearSlots = gearSlots ;
    }
    public int getGearSlots() {
        return this.gearSlots;
    }

    public void setMovementPenalty( Integer movementPenalty ) {
        this.movementPenalty = movementPenalty ;
    }
    public Integer getMovementPenalty() {
        return this.movementPenalty;
    }

    public void setNotes( String notes ) {
        this.notes = notes ;
    }
    public String getNotes() {
        return this.notes;
    }

    public EquipmentTypes getEquipmenttypes() {
        return this.equipmenttypes;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Armor[");
		sb.append("armorId=").append(armorId);
		sb.append(separator).append("equipmentTypeId=").append(equipmentTypeId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("armorModifier=").append(armorModifier);
		sb.append(separator).append("gearSlots=").append(gearSlots);
		sb.append(separator).append("movementPenalty=").append(movementPenalty);
		sb.append(separator).append("notes=").append(notes);
		sb.append("]");
		return sb.toString();
	}

}
