/*
 * Created on 2025-01-20 ( 17:03:21 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "BackgroundCorePowers"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="background_core_powers", schema="stargrave" )
public class BackgroundCorePowers implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="background_core_power_id", nullable=false)
    private int        backgroundCorePowerId ;

    //--- OTHER DATA FIELDS 
    @Column(name="background_id")
    private Integer    backgroundId ;

    @Column(name="power_id")
    private Integer    powerId ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="background_id", referencedColumnName="background_id", insertable=false, updatable=false)
    private Backgrounds backgrounds ; 

    @ManyToOne
    @JoinColumn(name="power_id", referencedColumnName="power_id", insertable=false, updatable=false)
    private Powers     powers ; 

    /**
     * Constructor
     */
    public BackgroundCorePowers() {
		super();
    }
    
    public void setBackgroundCorePowerId( int backgroundCorePowerId ) {
        this.backgroundCorePowerId = backgroundCorePowerId ;
    }
    public int getBackgroundCorePowerId() {
        return this.backgroundCorePowerId;
    }

    public void setBackgroundId( Integer backgroundId ) {
        this.backgroundId = backgroundId ;
    }
    public Integer getBackgroundId() {
        return this.backgroundId;
    }

    public void setPowerId( Integer powerId ) {
        this.powerId = powerId ;
    }
    public Integer getPowerId() {
        return this.powerId;
    }

    public Backgrounds getBackgrounds() {
        return this.backgrounds;
    } 

    public Powers getPowers() {
        return this.powers;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("BackgroundCorePowers[");
		sb.append("backgroundCorePowerId=").append(backgroundCorePowerId);
		sb.append(separator).append("backgroundId=").append(backgroundId);
		sb.append(separator).append("powerId=").append(powerId);
		sb.append("]");
		return sb.toString();
	}

}
