/*
 * Created on 2025-01-20 ( 17:03:21 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Backgrounds"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="backgrounds", schema="stargrave" )
public class Backgrounds implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="background_id", nullable=false)
    private int        backgroundId ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", nullable=false, length=50)
    private String     name ;

    @Column(name="description", length=2147483647)
    private String     description ;

    @Column(name="health_mod")
    private Integer    healthMod ;

    @Column(name="will_mod")
    private Integer    willMod ;

    @Column(name="move_mod")
    private Integer    moveMod ;

    @Column(name="fight_mod")
    private Integer    fightMod ;

    @Column(name="shoot_mod")
    private Integer    shootMod ;

    @Column(name="choices_allowed", nullable=false)
    private int        choicesAllowed ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="backgrounds")
    private List<BackgroundCorePowers> backgroundcorepowersList ; 

    @OneToMany(mappedBy="backgrounds")
    private List<BackgroundStatChoices> backgroundstatchoicesList ; 

    @OneToMany(mappedBy="backgrounds")
    private List<Characters> charactersList ; 

    /**
     * Constructor
     */
    public Backgrounds() {
		super();
    }
    
    public void setBackgroundId( int backgroundId ) {
        this.backgroundId = backgroundId ;
    }
    public int getBackgroundId() {
        return this.backgroundId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setHealthMod( Integer healthMod ) {
        this.healthMod = healthMod ;
    }
    public Integer getHealthMod() {
        return this.healthMod;
    }

    public void setWillMod( Integer willMod ) {
        this.willMod = willMod ;
    }
    public Integer getWillMod() {
        return this.willMod;
    }

    public void setMoveMod( Integer moveMod ) {
        this.moveMod = moveMod ;
    }
    public Integer getMoveMod() {
        return this.moveMod;
    }

    public void setFightMod( Integer fightMod ) {
        this.fightMod = fightMod ;
    }
    public Integer getFightMod() {
        return this.fightMod;
    }

    public void setShootMod( Integer shootMod ) {
        this.shootMod = shootMod ;
    }
    public Integer getShootMod() {
        return this.shootMod;
    }

    public void setChoicesAllowed( int choicesAllowed ) {
        this.choicesAllowed = choicesAllowed ;
    }
    public int getChoicesAllowed() {
        return this.choicesAllowed;
    }

    public List<BackgroundCorePowers> getBackgroundcorepowersList() {
        return this.backgroundcorepowersList;
    } 

    public List<BackgroundStatChoices> getBackgroundstatchoicesList() {
        return this.backgroundstatchoicesList;
    } 

    public List<Characters> getCharactersList() {
        return this.charactersList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Backgrounds[");
		sb.append("backgroundId=").append(backgroundId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("description=").append(description);
		sb.append(separator).append("healthMod=").append(healthMod);
		sb.append(separator).append("willMod=").append(willMod);
		sb.append(separator).append("moveMod=").append(moveMod);
		sb.append(separator).append("fightMod=").append(fightMod);
		sb.append(separator).append("shootMod=").append(shootMod);
		sb.append(separator).append("choicesAllowed=").append(choicesAllowed);
		sb.append("]");
		return sb.toString();
	}

}
