/*
 * Created on 2025-01-20 ( 17:03:21 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "BackgroundStatChoices"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="background_stat_choices", schema="stargrave" )
public class BackgroundStatChoices implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="background_stat_choice_id", nullable=false)
    private int        backgroundStatChoiceId ;

    //--- OTHER DATA FIELDS 
    @Column(name="background_id")
    private Integer    backgroundId ;

    @Column(name="stat_choice_id")
    private Integer    statChoiceId ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="background_id", referencedColumnName="background_id", insertable=false, updatable=false)
    private Backgrounds backgrounds ; 

    @ManyToOne
    @JoinColumn(name="stat_choice_id", referencedColumnName="stat_choice_id", insertable=false, updatable=false)
    private StatChoices statchoices ; 

    /**
     * Constructor
     */
    public BackgroundStatChoices() {
		super();
    }
    
    public void setBackgroundStatChoiceId( int backgroundStatChoiceId ) {
        this.backgroundStatChoiceId = backgroundStatChoiceId ;
    }
    public int getBackgroundStatChoiceId() {
        return this.backgroundStatChoiceId;
    }

    public void setBackgroundId( Integer backgroundId ) {
        this.backgroundId = backgroundId ;
    }
    public Integer getBackgroundId() {
        return this.backgroundId;
    }

    public void setStatChoiceId( Integer statChoiceId ) {
        this.statChoiceId = statChoiceId ;
    }
    public Integer getStatChoiceId() {
        return this.statChoiceId;
    }

    public Backgrounds getBackgrounds() {
        return this.backgrounds;
    } 

    public StatChoices getStatchoices() {
        return this.statchoices;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("BackgroundStatChoices[");
		sb.append("backgroundStatChoiceId=").append(backgroundStatChoiceId);
		sb.append(separator).append("backgroundId=").append(backgroundId);
		sb.append(separator).append("statChoiceId=").append(statChoiceId);
		sb.append("]");
		return sb.toString();
	}

}
