/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Characters"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="characters", schema="stargrave" )
public class Characters implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="character_id", nullable=false)
    private int        characterId ;

    //--- OTHER DATA FIELDS 
    @Column(name="crew_id")
    private Integer    crewId ;

    @Column(name="background_id")
    private Integer    backgroundId ;

    @Column(name="name", nullable=false, length=100)
    private String     name ;

    @Column(name="role_id")
    private Integer    roleId ;

    @Column(name="level", nullable=false)
    private int        level ;

    @Column(name="move", nullable=false)
    private int        move ;

    @Column(name="fight", nullable=false)
    private int        fight ;

    @Column(name="shoot", nullable=false)
    private int        shoot ;

    @Column(name="armor", nullable=false)
    private int        armor ;

    @Column(name="will", nullable=false)
    private int        will ;

    @Column(name="health", nullable=false)
    private int        health ;

    @Column(name="current_health")
    private Integer    currentHealth ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToMany
    @JoinTable( name="character_equipment", 
      joinColumns = @JoinColumn( name="character_id", referencedColumnName="character_id"),
      inverseJoinColumns = @JoinColumn( name="equipment_type_id", referencedColumnName="equipment_type_id") )
    private List<EquipmentTypes> equipmenttypesList ; 

    @OneToMany(mappedBy="characters")
    private List<CharacterPowers> characterpowersList ; 

    @ManyToOne
    @JoinColumn(name="background_id", referencedColumnName="background_id", insertable=false, updatable=false)
    private Backgrounds backgrounds ; 

    @ManyToOne
    @JoinColumn(name="crew_id", referencedColumnName="crew_id", insertable=false, updatable=false)
    private Crews      crews ; 

    @ManyToOne
    @JoinColumn(name="role_id", referencedColumnName="character_role_id", insertable=false, updatable=false)
    private CharacterRoles characterroles ; 

    /**
     * Constructor
     */
    public Characters() {
		super();
    }
    
    public void setCharacterId( int characterId ) {
        this.characterId = characterId ;
    }
    public int getCharacterId() {
        return this.characterId;
    }

    public void setCrewId( Integer crewId ) {
        this.crewId = crewId ;
    }
    public Integer getCrewId() {
        return this.crewId;
    }

    public void setBackgroundId( Integer backgroundId ) {
        this.backgroundId = backgroundId ;
    }
    public Integer getBackgroundId() {
        return this.backgroundId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setRoleId( Integer roleId ) {
        this.roleId = roleId ;
    }
    public Integer getRoleId() {
        return this.roleId;
    }

    public void setLevel( int level ) {
        this.level = level ;
    }
    public int getLevel() {
        return this.level;
    }

    public void setMove( int move ) {
        this.move = move ;
    }
    public int getMove() {
        return this.move;
    }

    public void setFight( int fight ) {
        this.fight = fight ;
    }
    public int getFight() {
        return this.fight;
    }

    public void setShoot( int shoot ) {
        this.shoot = shoot ;
    }
    public int getShoot() {
        return this.shoot;
    }

    public void setArmor( int armor ) {
        this.armor = armor ;
    }
    public int getArmor() {
        return this.armor;
    }

    public void setWill( int will ) {
        this.will = will ;
    }
    public int getWill() {
        return this.will;
    }

    public void setHealth( int health ) {
        this.health = health ;
    }
    public int getHealth() {
        return this.health;
    }

    public void setCurrentHealth( Integer currentHealth ) {
        this.currentHealth = currentHealth ;
    }
    public Integer getCurrentHealth() {
        return this.currentHealth;
    }

    public List<EquipmentTypes> getEquipmenttypesList() {
        return this.equipmenttypesList;
    } 

    public List<CharacterPowers> getCharacterpowersList() {
        return this.characterpowersList;
    } 

    public Backgrounds getBackgrounds() {
        return this.backgrounds;
    } 

    public Crews getCrews() {
        return this.crews;
    } 

    public CharacterRoles getCharacterroles() {
        return this.characterroles;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Characters[");
		sb.append("characterId=").append(characterId);
		sb.append(separator).append("crewId=").append(crewId);
		sb.append(separator).append("backgroundId=").append(backgroundId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("roleId=").append(roleId);
		sb.append(separator).append("level=").append(level);
		sb.append(separator).append("move=").append(move);
		sb.append(separator).append("fight=").append(fight);
		sb.append(separator).append("shoot=").append(shoot);
		sb.append(separator).append("armor=").append(armor);
		sb.append(separator).append("will=").append(will);
		sb.append(separator).append("health=").append(health);
		sb.append(separator).append("currentHealth=").append(currentHealth);
		sb.append("]");
		return sb.toString();
	}

}
