/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "CharacterRoles"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="character_roles", schema="stargrave" )
public class CharacterRoles implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="character_role_id", nullable=false)
    private int        characterRoleId ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", nullable=false, length=50)
    private String     name ;

    @Column(name="description", length=2147483647)
    private String     description ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="characterroles")
    private List<Characters> charactersList ; 

    /**
     * Constructor
     */
    public CharacterRoles() {
		super();
    }
    
    public void setCharacterRoleId( int characterRoleId ) {
        this.characterRoleId = characterRoleId ;
    }
    public int getCharacterRoleId() {
        return this.characterRoleId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public List<Characters> getCharactersList() {
        return this.charactersList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("CharacterRoles[");
		sb.append("characterRoleId=").append(characterRoleId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("description=").append(description);
		sb.append("]");
		return sb.toString();
	}

}
