/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;


/**
 * Composite primary key for entity "CharacterPowers" ( stored in table "character_powers" )
 *
 * @author Telosys
 *
 */
public class CharacterPowersId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private int        characterId ;
    
    private int        powerId ;
    
    /**
     * Constructor
     */
    public CharacterPowersId() {
        super();
    }

    /**
     * Constructor with values
     * @param characterId 
     * @param powerId 
     */
    public CharacterPowersId( Integer characterId, Integer powerId ) {
        super();
        this.characterId = characterId ;
        this.powerId = powerId ;
    }
    
    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setCharacterId( int value ) {
        this.characterId = value;
    }
    public int getCharacterId() {
        return this.characterId;
    }

    public void setPowerId( int value ) {
        this.powerId = value;
    }
    public int getPowerId() {
        return this.powerId;
    }


	@Override
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		CharacterPowersId other = (CharacterPowersId) obj; 
		//--- Attribute characterId
		if ( characterId != other.characterId ) return false ; 
		//--- Attribute powerId
		if ( powerId != other.powerId ) return false ; 
		return true; 
	} 
	@Override
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute characterId
		result = prime * result + characterId;
		//--- Attribute powerId
		result = prime * result + powerId;
		
		return result; 
	} 
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("CharacterPowers[");
		sb.append("characterId=").append(characterId);
		sb.append(separator).append("powerId=").append(powerId);
		sb.append(separator).append("activationNumber=").append(activationNumber);
		sb.append("]");
		return sb.toString();
	}

}
