/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;


import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "CharacterPowers"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="character_powers", schema="stargrave" )
@IdClass(CharacterPowersId.class)
public class CharacterPowers implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Column(name="character_id", nullable=false)
    private int        characterId ;

    @Id
    @Column(name="power_id", nullable=false)
    private int        powerId ;

    //--- OTHER DATA FIELDS 
    @Column(name="activation_number", nullable=false)
    private int        activationNumber ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="character_id", referencedColumnName="character_id", insertable=false, updatable=false)
    private Characters characters ; 

    @ManyToOne
    @JoinColumn(name="power_id", referencedColumnName="power_id", insertable=false, updatable=false)
    private Powers     powers ; 

    /**
     * Constructor
     */
    public CharacterPowers() {
		super();
    }
    
    public void setCharacterId( int characterId ) {
        this.characterId = characterId ;
    }
    public int getCharacterId() {
        return this.characterId;
    }

    public void setPowerId( int powerId ) {
        this.powerId = powerId ;
    }
    public int getPowerId() {
        return this.powerId;
    }

    public void setActivationNumber( int activationNumber ) {
        this.activationNumber = activationNumber ;
    }
    public int getActivationNumber() {
        return this.activationNumber;
    }

    public Characters getCharacters() {
        return this.characters;
    } 

    public Powers getPowers() {
        return this.powers;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("CharacterPowers[");
		sb.append("characterId=").append(characterId);
		sb.append(separator).append("powerId=").append(powerId);
		sb.append(separator).append("activationNumber=").append(activationNumber);
		sb.append("]");
		return sb.toString();
	}

}
