/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Creatures"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="creatures", schema="stargrave" )
public class Creatures implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="creature_id", nullable=false)
    private int        creatureId ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", nullable=false, length=100)
    private String     name ;

    @Column(name="move", nullable=false)
    private int        move ;

    @Column(name="fight", nullable=false)
    private int        fight ;

    @Column(name="shoot", nullable=false)
    private int        shoot ;

    @Column(name="armor", nullable=false)
    private int        armor ;

    @Column(name="will", nullable=false)
    private int        will ;

    @Column(name="health", nullable=false)
    private int        health ;

    @Column(name="description", length=2147483647)
    private String     description ;

    @Column(name="bounty_value")
    private Integer    bountyValue ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToMany
    @JoinTable( name="creature_attributes_link", 
      joinColumns = @JoinColumn( name="creature_id", referencedColumnName="creature_id"),
      inverseJoinColumns = @JoinColumn( name="attribute_id", referencedColumnName="attribute_id") )
    private List<CreatureAttributes> creatureattributesList ; 

    @OneToMany(mappedBy="creatures")
    private List<EncounterEntries> encounterentriesList ; 

    /**
     * Constructor
     */
    public Creatures() {
		super();
    }
    
    public void setCreatureId( int creatureId ) {
        this.creatureId = creatureId ;
    }
    public int getCreatureId() {
        return this.creatureId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setMove( int move ) {
        this.move = move ;
    }
    public int getMove() {
        return this.move;
    }

    public void setFight( int fight ) {
        this.fight = fight ;
    }
    public int getFight() {
        return this.fight;
    }

    public void setShoot( int shoot ) {
        this.shoot = shoot ;
    }
    public int getShoot() {
        return this.shoot;
    }

    public void setArmor( int armor ) {
        this.armor = armor ;
    }
    public int getArmor() {
        return this.armor;
    }

    public void setWill( int will ) {
        this.will = will ;
    }
    public int getWill() {
        return this.will;
    }

    public void setHealth( int health ) {
        this.health = health ;
    }
    public int getHealth() {
        return this.health;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setBountyValue( Integer bountyValue ) {
        this.bountyValue = bountyValue ;
    }
    public Integer getBountyValue() {
        return this.bountyValue;
    }

    public List<CreatureAttributes> getCreatureattributesList() {
        return this.creatureattributesList;
    } 

    public List<EncounterEntries> getEncounterentriesList() {
        return this.encounterentriesList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Creatures[");
		sb.append("creatureId=").append(creatureId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("move=").append(move);
		sb.append(separator).append("fight=").append(fight);
		sb.append(separator).append("shoot=").append(shoot);
		sb.append(separator).append("armor=").append(armor);
		sb.append(separator).append("will=").append(will);
		sb.append(separator).append("health=").append(health);
		sb.append(separator).append("description=").append(description);
		sb.append(separator).append("bountyValue=").append(bountyValue);
		sb.append("]");
		return sb.toString();
	}

}
