/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Crews"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="crews", schema="stargrave" )
public class Crews implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="crew_id", nullable=false)
    private int        crewId ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", nullable=false, length=100)
    private String     name ;

    @Column(name="credits")
    private Integer    credits ;

    @Column(name="experience")
    private Integer    experience ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="crews")
    private List<Characters> charactersList ; 

    @OneToMany(mappedBy="crews")
    private List<CrewShips> crewshipsList ; 

    @OneToMany(mappedBy="crews")
    private List<Soldiers> soldiersList ; 

    /**
     * Constructor
     */
    public Crews() {
		super();
    }
    
    public void setCrewId( int crewId ) {
        this.crewId = crewId ;
    }
    public int getCrewId() {
        return this.crewId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setCredits( Integer credits ) {
        this.credits = credits ;
    }
    public Integer getCredits() {
        return this.credits;
    }

    public void setExperience( Integer experience ) {
        this.experience = experience ;
    }
    public Integer getExperience() {
        return this.experience;
    }

    public List<Characters> getCharactersList() {
        return this.charactersList;
    } 

    public List<CrewShips> getCrewshipsList() {
        return this.crewshipsList;
    } 

    public List<Soldiers> getSoldiersList() {
        return this.soldiersList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Crews[");
		sb.append("crewId=").append(crewId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("credits=").append(credits);
		sb.append(separator).append("experience=").append(experience);
		sb.append("]");
		return sb.toString();
	}

}
