/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "CrewShips"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="crew_ships", schema="stargrave" )
public class CrewShips implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ship_id", nullable=false)
    private int        shipId ;

    //--- OTHER DATA FIELDS 
    @Column(name="crew_id")
    private Integer    crewId ;

    @Column(name="name", nullable=false, length=100)
    private String     name ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="crewships")
    private List<CrewShipUpgrades> crewshipupgradesList ; 

    @ManyToOne
    @JoinColumn(name="crew_id", referencedColumnName="crew_id", insertable=false, updatable=false)
    private Crews      crews ; 

    /**
     * Constructor
     */
    public CrewShips() {
		super();
    }
    
    public void setShipId( int shipId ) {
        this.shipId = shipId ;
    }
    public int getShipId() {
        return this.shipId;
    }

    public void setCrewId( Integer crewId ) {
        this.crewId = crewId ;
    }
    public Integer getCrewId() {
        return this.crewId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public List<CrewShipUpgrades> getCrewshipupgradesList() {
        return this.crewshipupgradesList;
    } 

    public Crews getCrews() {
        return this.crews;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("CrewShips[");
		sb.append("shipId=").append(shipId);
		sb.append(separator).append("crewId=").append(crewId);
		sb.append(separator).append("name=").append(name);
		sb.append("]");
		return sb.toString();
	}

}
