/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "EncounterTables"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="encounter_tables", schema="stargrave" )
public class EncounterTables implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="encounter_table_id", nullable=false)
    private int        encounterTableId ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", nullable=false, length=100)
    private String     name ;

    @Column(name="description", length=2147483647)
    private String     description ;

    @Column(name="active")
    private Boolean    active ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="encountertables")
    private List<EncounterEntries> encounterentriesList ; 

    /**
     * Constructor
     */
    public EncounterTables() {
		super();
    }
    
    public void setEncounterTableId( int encounterTableId ) {
        this.encounterTableId = encounterTableId ;
    }
    public int getEncounterTableId() {
        return this.encounterTableId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setActive( Boolean active ) {
        this.active = active ;
    }
    public Boolean getActive() {
        return this.active;
    }

    public List<EncounterEntries> getEncounterentriesList() {
        return this.encounterentriesList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("EncounterTables[");
		sb.append("encounterTableId=").append(encounterTableId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("description=").append(description);
		sb.append(separator).append("active=").append(active);
		sb.append("]");
		return sb.toString();
	}

}
