/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "EquipmentTypes"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="equipment_types", schema="stargrave" )
public class EquipmentTypes implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="equipment_type_id", nullable=false)
    private int        equipmentTypeId ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", nullable=false, length=50)
    private String     name ;

    @Column(name="slot_type_id")
    private Integer    slotTypeId ;

    @Column(name="description", length=2147483647)
    private String     description ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="equipmenttypes")
    private List<Armor> armorList ; 

    @ManyToMany
    @JoinTable( name="character_equipment", 
      joinColumns = @JoinColumn( name="equipment_type_id", referencedColumnName="equipment_type_id"),
      inverseJoinColumns = @JoinColumn( name="character_id", referencedColumnName="character_id") )
    private List<Characters> charactersList ; 

    @ManyToOne
    @JoinColumn(name="slot_type_id", referencedColumnName="equipment_slot_id", insertable=false, updatable=false)
    private EquipmentSlots equipmentslots ; 

    @ManyToMany
    @JoinTable( name="soldier_equipment", 
      joinColumns = @JoinColumn( name="equipment_type_id", referencedColumnName="equipment_type_id"),
      inverseJoinColumns = @JoinColumn( name="soldier_id", referencedColumnName="soldier_id") )
    private List<Soldiers> soldiersList ; 

    @OneToMany(mappedBy="equipmenttypes")
    private List<Weapons> weaponsList ; 

    /**
     * Constructor
     */
    public EquipmentTypes() {
		super();
    }
    
    public void setEquipmentTypeId( int equipmentTypeId ) {
        this.equipmentTypeId = equipmentTypeId ;
    }
    public int getEquipmentTypeId() {
        return this.equipmentTypeId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setSlotTypeId( Integer slotTypeId ) {
        this.slotTypeId = slotTypeId ;
    }
    public Integer getSlotTypeId() {
        return this.slotTypeId;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public List<Armor> getArmorList() {
        return this.armorList;
    } 

    public List<Characters> getCharactersList() {
        return this.charactersList;
    } 

    public EquipmentSlots getEquipmentslots() {
        return this.equipmentslots;
    } 

    public List<Soldiers> getSoldiersList() {
        return this.soldiersList;
    } 

    public List<Weapons> getWeaponsList() {
        return this.weaponsList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("EquipmentTypes[");
		sb.append("equipmentTypeId=").append(equipmentTypeId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("slotTypeId=").append(slotTypeId);
		sb.append(separator).append("description=").append(description);
		sb.append("]");
		return sb.toString();
	}

}
