/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "PowerCategories"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="power_categories", schema="stargrave" )
public class PowerCategories implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="power_category_id", nullable=false)
    private int        powerCategoryId ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", nullable=false, length=50)
    private String     name ;

    @Column(name="description", length=2147483647)
    private String     description ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="powercategories")
    private List<Powers> powersList ; 

    /**
     * Constructor
     */
    public PowerCategories() {
		super();
    }
    
    public void setPowerCategoryId( int powerCategoryId ) {
        this.powerCategoryId = powerCategoryId ;
    }
    public int getPowerCategoryId() {
        return this.powerCategoryId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public List<Powers> getPowersList() {
        return this.powersList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("PowerCategories[");
		sb.append("powerCategoryId=").append(powerCategoryId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("description=").append(description);
		sb.append("]");
		return sb.toString();
	}

}
