/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Powers"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="powers", schema="stargrave" )
public class Powers implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="power_id", nullable=false)
    private int        powerId ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", nullable=false, length=50)
    private String     name ;

    @Column(name="activation_number", nullable=false)
    private int        activationNumber ;

    @Column(name="strain", nullable=false)
    private int        strain ;

    @Column(name="category_id")
    private Integer    categoryId ;

    @Column(name="description", length=2147483647)
    private String     description ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="powers")
    private List<BackgroundCorePowers> backgroundcorepowersList ; 

    @OneToMany(mappedBy="powers")
    private List<CharacterPowers> characterpowersList ; 

    @ManyToOne
    @JoinColumn(name="category_id", referencedColumnName="power_category_id", insertable=false, updatable=false)
    private PowerCategories powercategories ; 

    /**
     * Constructor
     */
    public Powers() {
		super();
    }
    
    public void setPowerId( int powerId ) {
        this.powerId = powerId ;
    }
    public int getPowerId() {
        return this.powerId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setActivationNumber( int activationNumber ) {
        this.activationNumber = activationNumber ;
    }
    public int getActivationNumber() {
        return this.activationNumber;
    }

    public void setStrain( int strain ) {
        this.strain = strain ;
    }
    public int getStrain() {
        return this.strain;
    }

    public void setCategoryId( Integer categoryId ) {
        this.categoryId = categoryId ;
    }
    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public List<BackgroundCorePowers> getBackgroundcorepowersList() {
        return this.backgroundcorepowersList;
    } 

    public List<CharacterPowers> getCharacterpowersList() {
        return this.characterpowersList;
    } 

    public PowerCategories getPowercategories() {
        return this.powercategories;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Powers[");
		sb.append("powerId=").append(powerId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("activationNumber=").append(activationNumber);
		sb.append(separator).append("strain=").append(strain);
		sb.append(separator).append("categoryId=").append(categoryId);
		sb.append(separator).append("description=").append(description);
		sb.append("]");
		return sb.toString();
	}

}
