/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "ShipUpgrades"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="ship_upgrades", schema="stargrave" )
public class ShipUpgrades implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ship_upgrade_id", nullable=false)
    private int        shipUpgradeId ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", nullable=false, length=100)
    private String     name ;

    @Column(name="cost", nullable=false)
    private int        cost ;

    @Column(name="description", length=2147483647)
    private String     description ;

    @Column(name="max_quantity")
    private Integer    maxQuantity ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="shipupgrades")
    private List<CrewShipUpgrades> crewshipupgradesList ; 

    /**
     * Constructor
     */
    public ShipUpgrades() {
		super();
    }
    
    public void setShipUpgradeId( int shipUpgradeId ) {
        this.shipUpgradeId = shipUpgradeId ;
    }
    public int getShipUpgradeId() {
        return this.shipUpgradeId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setCost( int cost ) {
        this.cost = cost ;
    }
    public int getCost() {
        return this.cost;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setMaxQuantity( Integer maxQuantity ) {
        this.maxQuantity = maxQuantity ;
    }
    public Integer getMaxQuantity() {
        return this.maxQuantity;
    }

    public List<CrewShipUpgrades> getCrewshipupgradesList() {
        return this.crewshipupgradesList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("ShipUpgrades[");
		sb.append("shipUpgradeId=").append(shipUpgradeId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("cost=").append(cost);
		sb.append(separator).append("description=").append(description);
		sb.append(separator).append("maxQuantity=").append(maxQuantity);
		sb.append("]");
		return sb.toString();
	}

}
