/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "SoldierTypes"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="soldier_types", schema="stargrave" )
public class SoldierTypes implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="soldier_type_id", nullable=false)
    private int        soldierTypeId ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", nullable=false, length=50)
    private String     name ;

    @Column(name="class_id")
    private Integer    classId ;

    @Column(name="move", nullable=false)
    private int        move ;

    @Column(name="fight", nullable=false)
    private int        fight ;

    @Column(name="shoot", nullable=false)
    private int        shoot ;

    @Column(name="armor", nullable=false)
    private int        armor ;

    @Column(name="will", nullable=false)
    private int        will ;

    @Column(name="health", nullable=false)
    private int        health ;

    @Column(name="cost", nullable=false)
    private int        cost ;

    @Column(name="notes", length=2147483647)
    private String     notes ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="class_id", referencedColumnName="soldier_class_id", insertable=false, updatable=false)
    private SoldierClasses soldierclasses ; 

    @OneToMany(mappedBy="soldiertypes")
    private List<Soldiers> soldiersList ; 

    /**
     * Constructor
     */
    public SoldierTypes() {
		super();
    }
    
    public void setSoldierTypeId( int soldierTypeId ) {
        this.soldierTypeId = soldierTypeId ;
    }
    public int getSoldierTypeId() {
        return this.soldierTypeId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setClassId( Integer classId ) {
        this.classId = classId ;
    }
    public Integer getClassId() {
        return this.classId;
    }

    public void setMove( int move ) {
        this.move = move ;
    }
    public int getMove() {
        return this.move;
    }

    public void setFight( int fight ) {
        this.fight = fight ;
    }
    public int getFight() {
        return this.fight;
    }

    public void setShoot( int shoot ) {
        this.shoot = shoot ;
    }
    public int getShoot() {
        return this.shoot;
    }

    public void setArmor( int armor ) {
        this.armor = armor ;
    }
    public int getArmor() {
        return this.armor;
    }

    public void setWill( int will ) {
        this.will = will ;
    }
    public int getWill() {
        return this.will;
    }

    public void setHealth( int health ) {
        this.health = health ;
    }
    public int getHealth() {
        return this.health;
    }

    public void setCost( int cost ) {
        this.cost = cost ;
    }
    public int getCost() {
        return this.cost;
    }

    public void setNotes( String notes ) {
        this.notes = notes ;
    }
    public String getNotes() {
        return this.notes;
    }

    public SoldierClasses getSoldierclasses() {
        return this.soldierclasses;
    } 

    public List<Soldiers> getSoldiersList() {
        return this.soldiersList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("SoldierTypes[");
		sb.append("soldierTypeId=").append(soldierTypeId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("classId=").append(classId);
		sb.append(separator).append("move=").append(move);
		sb.append(separator).append("fight=").append(fight);
		sb.append(separator).append("shoot=").append(shoot);
		sb.append(separator).append("armor=").append(armor);
		sb.append(separator).append("will=").append(will);
		sb.append(separator).append("health=").append(health);
		sb.append(separator).append("cost=").append(cost);
		sb.append(separator).append("notes=").append(notes);
		sb.append("]");
		return sb.toString();
	}

}
