/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "StatChoices"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="stat_choices", schema="stargrave" )
public class StatChoices implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="stat_choice_id", nullable=false)
    private int        statChoiceId ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", nullable=false, length=50)
    private String     name ;

    @Column(name="description", length=2147483647)
    private String     description ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="statchoices")
    private List<BackgroundStatChoices> backgroundstatchoicesList ; 

    /**
     * Constructor
     */
    public StatChoices() {
		super();
    }
    
    public void setStatChoiceId( int statChoiceId ) {
        this.statChoiceId = statChoiceId ;
    }
    public int getStatChoiceId() {
        return this.statChoiceId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public List<BackgroundStatChoices> getBackgroundstatchoicesList() {
        return this.backgroundstatchoicesList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("StatChoices[");
		sb.append("statChoiceId=").append(statChoiceId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("description=").append(description);
		sb.append("]");
		return sb.toString();
	}

}
