/*
 * Created on 2025-01-20 ( 17:03:22 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.eg0n.startools.telosys.persistence.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Weapons"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="weapons", schema="stargrave" )
public class Weapons implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="weapon_id", nullable=false)
    private int        weaponId ;

    //--- OTHER DATA FIELDS 
    @Column(name="equipment_type_id")
    private Integer    equipmentTypeId ;

    @Column(name="name", nullable=false, length=50)
    private String     name ;

    @Column(name="damage_modifier")
    private Integer    damageModifier ;

    @Column(name="max_range")
    private Integer    maxRange ;

    @Column(name="gear_slots", nullable=false)
    private int        gearSlots ;

    @Column(name="notes", length=2147483647)
    private String     notes ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="equipment_type_id", referencedColumnName="equipment_type_id", insertable=false, updatable=false)
    private EquipmentTypes equipmenttypes ; 

    /**
     * Constructor
     */
    public Weapons() {
		super();
    }
    
    public void setWeaponId( int weaponId ) {
        this.weaponId = weaponId ;
    }
    public int getWeaponId() {
        return this.weaponId;
    }

    public void setEquipmentTypeId( Integer equipmentTypeId ) {
        this.equipmentTypeId = equipmentTypeId ;
    }
    public Integer getEquipmentTypeId() {
        return this.equipmentTypeId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setDamageModifier( Integer damageModifier ) {
        this.damageModifier = damageModifier ;
    }
    public Integer getDamageModifier() {
        return this.damageModifier;
    }

    public void setMaxRange( Integer maxRange ) {
        this.maxRange = maxRange ;
    }
    public Integer getMaxRange() {
        return this.maxRange;
    }

    public void setGearSlots( int gearSlots ) {
        this.gearSlots = gearSlots ;
    }
    public int getGearSlots() {
        return this.gearSlots;
    }

    public void setNotes( String notes ) {
        this.notes = notes ;
    }
    public String getNotes() {
        return this.notes;
    }

    public EquipmentTypes getEquipmenttypes() {
        return this.equipmenttypes;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Weapons[");
		sb.append("weaponId=").append(weaponId);
		sb.append(separator).append("equipmentTypeId=").append(equipmentTypeId);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("damageModifier=").append(damageModifier);
		sb.append(separator).append("maxRange=").append(maxRange);
		sb.append(separator).append("gearSlots=").append(gearSlots);
		sb.append(separator).append("notes=").append(notes);
		sb.append("]");
		return sb.toString();
	}

}
